### ISSUE TITLE
level 37: a branch called "if this commit gets pushed you have lost the level" should be committed

### ISSUE THREAD

**Issue by noamraph** [Gazler/githug#164]

**Comment by AbuDarian** [comment]
I also find this one very confusing. I looked in to pushing a singel commit, pushing a single branch and every other possibillity I can think of. But I always seem to get "The solution isn't quite right"....any advice?

**Comment by Gazler** [comment]
@AbuDarian the point is to commit a different branch to the repository. You can see the solution at https://github.com/Gazler/githug/blob/3b0cccdefb3fd2c81800b5d5e26171d334b1be1f/spec/githug_spec.rb#L220

**Comment by AbuDarian** [comment]
@Gazler :Your solution is the first one I tried. But it seems to be a different kind of problem.

![image](https://cloud.githubusercontent.com/assets/8581487/6102598/957b0114-b039-11e4-921c-883821ff8175.png)

**Comment by Gazler** [comment]
I see the problem - it is using wc which is a Unix command on windows. An
issue was raised recently at https://github.com/Gazler/githug/issues/186

**Comment by AbuDarian** [comment]
My selfconfidence was shot for about 3 days....:-) its good to know the problem lay elseware

**Comment by Gazler** [comment]
@AbuDarian sorry about that! I'll continue communication on the other issue.
