### ISSUE TITLE
Test failed.

### ISSUE THREAD

**Issue by hkliya** [Gazler/githug#179]
Githug is a very useful tool to learn git. I like to use it in git workshop.
But many developers are not good at english. So I would like to translate description and hints to Chinese .
I also found that there is a i18n branch, but it looks like out of date for a long time.

When I run `rake` on my Mac, it failed with:
```
undefined local variable or method `mock' for #<RSpec::ExampleGroups::GithugRepository::MethodMissing:0x007fa6c329e6b0>
```
I am not an expert in Ruby, could you tell me what is wrong?

**Comment by Gazler** [comment]
@hkliya I just tried running rake on the i18n branch and all the tests passed. Could you tell me what version of ruby you are on?

That branch hasn't been updated in a long time, I can't remember the exact status of it. I have however rebased master into a new branch called `0.4-i18n` - this is up to date with master but has the i18n changes.

There is currently no way to set the locale, so you will have to manually set the value in `.profile.yml` - let me know if this is enough to get you started.

**Comment by hkliya** [comment]
@Gazler I am using `ruby 2.0.0p247`.
That is very helpful, I will work on the branch. Thank you!
