### ISSUE TITLE
mac OS X 10.10.1 >> githug fails upon entering git_hug directory 

### ISSUE THREAD

**Issue by ajharris** [Gazler/githug#181]
The program runs if I am outside the git_hug directory but instructs me to cd into the git_hug directory.  However, once I do, I get the following error (I have truncated it at the .rvm indicator for privacy)

    /.rvm/gems/ruby-2.0.0-p598/gems/githug-0.4.3/lib/githug/profile.rb:17:in `merge': no implicit conversion of false into Hash (TypeError)

**Comment by Gazler** [comment]
@ajharris Could you please confirm that you have a `.profile` file in your `git_hug` directory? It should exist if you are getting that error, could you please paste the contents of that file here?

**Comment by ajharris** [comment]
.profile.yml exists however it is just an empty file

**Comment by Gazler** [comment]
Could you please trying removing your `git_hug` directory and running the `githug` command again?

**Comment by ajharris** [comment]
removed and reinstalled, got the following error:

    No githug directory found, do you wish to create one? [yn]  y
    Welcome to Githug!
    /Users/andrewharris/.rvm/gems/ruby-2.1.5/gems/githug-0.4.3/lib/githug/profile.rb:48:in `block in save': undefined method `dump' for Psych:Module (NoMethodError)

**Comment by Gazler** [comment]
I can't seem to replicate the issue. It could be a problem with the YAML library, could you please paste the output of `gem list | grep psych`

You can manually create a `git_hug` directory by doing:

```
mkdir git_hug
```

Then create the following files:

.gitignore

```
.profile.yml
.gitignore
```

.profile

```
---
:level: init
:current_attempts: 0
:current_hint_index: 0
:current_levels:
- 
- init
- config
- add
- commit
- clone
- clone_to_folder
- ignore
- include
- status
- number_of_files_committed
- rm
- rm_cached
- stash
- rename
- restructure
- log
- tag
- push_tags
- commit_amend
- commit_in_future
- reset
- reset_soft
- checkout_file
- remote
- remote_url
- pull
- remote_add
- push
- diff
- blame
- branch
- checkout
- checkout_tag
- checkout_tag_over_branch
- branch_at
- delete_branch
- push_branch
- merge
- fetch
- rebase
- repack
- cherry-pick
- grep
- rename_commit
- squash
- merge_squash
- reorder
- bisect
- stage_lines
- find_old_branch
- revert
- restore
- conflict
- contribute
:completed_levels:
- 
```

Please let me know if this works.

**Comment by mossiso** [comment]
I'm also on a Mac 10.10.1. I was getting the same errors as above. I also had an empty .profile and no .gitignore when running the `githug` command initially. I added the .profile and .gitignore files as directed above but now get this error:

```/Users/username/.rvm/gems/ruby-2.1.5@global/gems/githug-0.4.3/lib/githug/profile.rb:17:in `settings': private method `load' called for Psych:Module (NoMethodError)```

Also,
 
    $ gem list | grep psych
    psych (2.0.8, 2.0.5)

**Comment by Gazler** [comment]
@mossiso I cannot replicate this issue on Linux (Mint 17) - I'll try and get a hold of a mac and see if I can replicate it.

**Comment by mossiso** [comment]
Yes, odd. I have it working fine on a clean CentOS 6.5 VM.
