### ISSUE TITLE
gem install githug  not working

### ISSUE THREAD

**Issue by mirage1993** [Gazler/githug#182]
OS:CentOS 6.4
ruby:ruby 1.8.7 (2013-06-27 patchlevel 374) [i386-linux]

![default](https://cloud.githubusercontent.com/assets/8112645/5719740/2596abfc-9b56-11e4-8b37-1050f26ce90c.JPG)

No response~

**Comment by Gazler** [comment]
@mirage1993 Have you tried installing another gem? What is the response of `gem install rspec` or `gem install rails` or something similar?

**Comment by mirage1993** [comment]
@Gazler  thanks ! 
It need 10 minutes to finish installation, I'm from china,so the network is not very fast because of the GFW.
