### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by ccysfn** [Gazler/githug#184]
Name: commit_in_future
Level: 20 
i cant find the answer,just help me

**Comment by microdog** [comment]
```git commit -m "Commit in future" --date="`date -v+1H`"```

This should work. :)

See http://git-scm.com/docs/git-commit

**Comment by ccysfn** [comment]
thx a lot !     i use the following command 
git commit -m "xx"--date 2015-01-25T11:11:11
In the manual there is " --date=<date>  "   ,and i typed in ,it return the  "syntax error". so i use the command above

**Comment by microdog** [comment]
Your datetime string should be protected by quotes. Just like `-m` or `--message=<msg>` option.
For example:

```git commit -m "Message here" --date="Sat Jan 24 14:16:37 CST 2015"```

```git commit --message="Message here" --date="Sat Jan 24 14:16:37 CST 2015"```

BTW. There is another way to achieve the goal: using environment variables.

```env GIT_AUTHOR_DATE="Sat Jan 24 14:16:37 CST 2016" git commit -m "Commit in future"```

See http://git-scm.com/docs/git-commit#_date_formats
