### ISSUE TITLE
Level 28 (Errno::ENAMETOOLONG)

### ISSUE THREAD

**Issue by mtam2** [Gazler/githug#188]
Currently using c9.io Ubuntu environment
Full error log: https://goo.gl/7bRzm3

>githug reset
resetting level
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1365:in `mkdir': File name too long @ dir_s_mkdir - /home/ubuntu/workspace/git_hug/d20150902-9102-ooqs0q/./d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q/d20150902-9102-ooqs0q (Errno::ENAMETOOLONG)
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1365:in `copy'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:471:in `block in copy_entry'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1497:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1497:in `wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'

**Comment by Gazler** [comment]
That's quite a stacktrace. I'll see if I can figure out what it causing it.

**Comment by Gazler** [comment]
Just attempted this on c9.io myself and it seems to be working fine so I am closing this issue. Please comment here if you encounter the problem again.
