### ISSUE TITLE
level 51 error when use git v2.5.0

### ISSUE THREAD

**Issue by kunyan** [Gazler/githug#193]
>Name: revert
>Level: 51
>Difficulty: ****
>
>You have committed several times but want to undo the middle commit.
>All commits have been pushed, so you can't change existing history.

```sh
git revert HEAD~1 --no-edit
```

>Sorry, this solution is not quite right!

I think this PR would fix it
https://github.com/Gazler/githug/pull/189

**Comment by Gazler** [comment]
Thanks for raising this. I'll look at getting this fixed before the next release.

**Comment by fighterleslie** [comment]
FYI, I ran into the same problem at level 51. My git version is 2.6.2 (Ubuntu 14.04 LTS).

**Comment by Gazler** [comment]
Closed via https://github.com/Gazler/githug/pull/194
