### ISSUE TITLE
Could not find githug (>= 0)

### ISSUE THREAD

**Issue by lizhenguo** [Gazler/githug#202]
I am new to ruby. So I can't find what the problem is. So this what problem I met: when I invoke `githug`
```
/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find githug (>= 0) amongst [gem-wrappers-1.2.7, minitest-5.4.3, posix-spawn-0.3.11, power_assert-0.2.2, pygments.rb-0.6.3, redcarpet-3.3.2, rvm-1.11.3.9, test-unit-3.0.8, yajl-ruby-1.2.1] (Gem::LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
	from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
	from /usr/local/bin/githug:22:in `<main>'
```
The ruby version is: 
```
#ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

The gem version is:  
```
#gem --version
2.4.8
```

**Comment by Gazler** [comment]
Hey,

Have you run `gem install githug`?

**Comment by lizhenguo** [comment]
Yes, of course@Gazler

**Comment by Gazler** [comment]
@lizhenguo What is the result of `which githug`?

**Comment by lizhenguo** [comment]
/usr/local/bin/githug, @Gazler

**Comment by Gazler** [comment]
@lizhenguo Could you also provide the outputs of `which ruby`? Which OS are you using btw?

**Comment by lizhenguo** [comment]
the output of `uname -a`: Linux android-83d83892ef3829cd 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`which ruby`: /home/lizhenguo/.rvm/rubies/ruby-2.2.1/bin/ruby

**Comment by Gazler** [comment]
@lizhenguo Looks like there may be an issue with rvm. Did you install `githug` when `rvm` wasn't being used?

Please try running `gem install githug` again and provide the output.

**Comment by lizhenguo** [comment]
the output is
```
Successfully installed githug-0.4.8
1 gem installed
Installing ri documentation for githug-0.4.8...
Installing RDoc documentation for githug-0.4.8...
``` 
@Gazler

**Comment by Gazler** [comment]
@lizhenguo Ok, if it still isn't working, there are a few more things to try, what are the results of `which gem` and `which githug` now?

**Comment by lizhenguo** [comment]
`which gem`: /home/lizhenguo/.rvm/rubies/ruby-2.2.1/bin/gem
`which githug`: /usr/local/bin/githug
@Gazler

**Comment by Gazler** [comment]
@lizhenguo Try running `mv /usr/local/bin/githug /usr/local/bin/githug.bak` (you will probably need root).

Then run `githug`

If it works, delete the `githug.bak` file you made. If it doesn't work then let me know the output of `which githug`.

**Comment by lizhenguo** [comment]
@Gazler When I try `githug` after moving, the output is `bash: /usr/local/bin/githug: No such file or directory`

**Comment by Gazler** [comment]
Ok, can you try `gem install githug` again and see if it works?

If not, what is the result of `rvm gemdir` and `rvm ls $(rvm gemdir)/bin`

**Comment by lizhenguo** [comment]
Yes, `gem install githug` works, @Gazler

**Comment by Gazler** [comment]
@lizhenguo So it works now? RVM works by installing gems to your home directory, this allows multiple versions of ruby to be used at once. However RVM will not share system gems. It looks like you installed the gem as root, but then used rvm for ruby, resulting in the gem being installed, but unusable by the binary/

**Comment by georgiana-gligor** [comment]
I had the same issue. Installing the gem worked,
```bash
$ gem install githug
Successfully installed githug-0.4.8
Parsing documentation for githug-0.4.8
1 gem installed
```
while invoking didn't:
```bash
$ githug                                                        
zsh: command not found: githug

$ which githug                                                  
githug not found
```

In my case the problem was solved by installing with administrative privileges:
```bash
$ sudo gem install githug 

$ githug                                                        
********************************************************************************
*                                    Githug                                    *
********************************************************************************
No githug directory found, do you wish to create one? [yn]  
```
