### ISSUE TITLE
False failure on Stage 7

### ISSUE THREAD

**Issue by cwrinn** [Gazler/githug#207]
In .gitignore, I put:
**/*.swp

Which successfully ignores ALL .swp files in the repository.

The game only accepted '*.swp'.

A better evaluation is probably to check the output of 'git status' for any untracked .swp files.

**Comment by Gazler** [comment]
Thanks for the report.

If you are happy looking at changing this then feel free to submit a PR, your solution definitely sounds like a better way of checking. If not then I can look in to doing it.

**Comment by pallxk** [comment]
> The text editor 'vim' creates files ending in `.swp` (swap files) for all files that are currently open.

I believe the expectation of this level is to ignore files ending in `.swp` instead of files named as `.swp`.

I've made a PR (#216) to clarify the level description (no level check logic changed).
