### ISSUE TITLE
Level2 not check local config

### ISSUE THREAD

**Issue by eZioPan** [Gazler/githug#213]
Hi,
I find that you program only check global/system config, but no local config, so when I use
git config --local user.name
and
git config --local user.email

it don't respond right.

**Comment by Gazler** [comment]
Thanks for the report. I'll check it out.

**Comment by mhatvan** [comment]
Hey man, I like githug, but cant get past level 2, which sucks.
It doesnt matter if I try --global or --local, user.name/email or core.name/email, any combination, it always tells me the solution is not right?

**Comment by Gazler** [comment]
@mhatvan Are you typing in the same values as the results of:

    git config --global user.name
    git config --global user.emal

**Comment by mhatvan** [comment]
i used ruby console for githug cmds and git bash for git cmds, that was the problem ;) 
solved it by fixing the PATH variables accordingly! now already around lvl 40 :D
thanks for the response though!
