### ISSUE TITLE
Windows 10, error installing githug: "rake" conflicts

### ISSUE THREAD

**Issue by splanard** [Gazler/githug#244]
I tried to install githug on Windows 10.
First, I installed Ruby 2.5. Seamed to work fine.
Then, `gem install github` and I got the following :
```
$ gem install githug
ERROR:  Error installing githug:
        "rake" from rake conflicts with C:/Dev/resources/ruby/Ruby25-x64/bin/rake
```
Did someone have the same problem ?
(I'm totally noob to Ruby...)

**Comment by Gazler** [comment]
I don't use Windows, but perhaps following this guide up until the point of installing rails, and then installing githug may work.

https://gorails.com/setup/windows/10

**Comment by splanard** [comment]
A `-f` option in the install command did the trick... I don't know why (and I don't really care ^^')
Githug seems to be installed, but `githug` command just do nothing... :-(
