### ISSUE TITLE
Answer of rename_commit is confusing

### ISSUE THREAD

**Issue by vikrant-pune** [Gazler/githug#255]
Hi,

We have problem statement as 'Correct the typo in the message of your first (non-root) commit.'
I'm assuming this points to second log "First coommit" entry from bellow list with typo:

    `~/githug-test/git_hug$ git log 
    commit 5ae6bca7768104998ac8aaa93d40ad6f42b3dd90 (HEAD -> master)
    Author: vikrant pawar
    Date:   Sat Feb 16 20:30:15 2019 +0530

    Second commit

    commit f877b1e0aa22ed94907de7d06d3b2c470581bb32
    Author: vikrant pawar
    Date:   Sat Feb 16 20:30:15 2019 +0530

    First coommit

    commit f03505f0316ea3eae2eaa8533bd044a79883fd8f
    Author: vikrant pawar 
    Date:   Sat Feb 16 20:30:15 2019 +0530

    Initial commit

However even after fixing it, code doesn't mark it as success .. 
While digging code I found we are using 
`repo.commits[1].message == "First commit"`
which is checking string 'Second commit' to 'First commit'.

wanted to confirm if I'm missing anything

**Comment by BreakBB** [comment]
I had no problems with this level. What I did was:

- `git rebase -i HEAD~2`.
- Then changed the "pick 6d7c69b First coommit" to "r 6d7c69b First coommit".
- Fixed the commit message afterwards to "First commit".
- run `githug`

**Comment by gchazot** [comment]
Same as #258

**Comment by gchazot** [comment]
Fix in #276

**Comment by Gazler** [comment]
Fixed in #276
