### ISSUE TITLE
Stage 14 not accepting the answer even though it's presumably correct

### ISSUE THREAD

**Issue by rbennum** [Gazler/githug#286]
Hello. First of all, thank you for developing the tool for everyone to learn Git. I have a problem with the solution of Stage 14. I assume it's just a simple file renaming using `git mv file1 file2` (just an example, it's also been backed up by [this article](https://www.tobscore.com/githug-what-is-it/)), but apparently, my solution isn't quite right. I already looked up `githug hint`, and tried each of the flags but little or to no avail. If there is someone who could help me, I would really appreciate it.

**Comment by nonchalant-enthusiast** [comment]
@rbennum turns out you need to commit the creation of `oldfile.txt` first. so the full solution looks like this:
```
git commit
git mv file1 file2
```
needed to look into the code of solution for this. the hint is only part of the solution. maybe that's why this level ranked as "***" :D

**Comment by rbennum** [comment]
@nonchalant-enthusiast alright it really works! Thank you so much for answering my question. Have a nice day.

**Comment by itsgoadsoul** [comment]
I dont think this issue should be closed. This level needs to be reworked somehow, because there is no way, that anyone can solve this with the text provided.

The level wants me to rename the files.
why would i ever commit anything in this task?
