### ISSUE TITLE
DISCUSSION: New level-set branch based on Git Immersion by Jim Weirich

### ISSUE THREAD

**Issue by odiraneyya** [Gazler/githug#315]
Hey @Gazler,

Thanks for merging the pull request.

Since you seemed to see value in what I did, I thought I would use this as an opportunity to discuss with you creating a branch with an alternative set of levels.

The idea here is to target the git beginner, rather than the professional programmer, while providing what serves to be a side reading, in the form of an online tutorial (please see the [Git Immersion](https://gitimmersion.com) website).

In my opinion, this will leverage the level set to act as an actual curriculum, with a part reading, part practice.

_Possible issues here:_
- This might have already been considered and avoided for licensing issues ([Jim Weirich](https://en.wikipedia.org/wiki/Jim_Weirich)'s work is based on an attribution-based, CC license)
- Seeing that the number of levels/labs is 54, I am wondering if our levels are somehow related to, or inspired by, the Git Immersion website?
- Implemeting some of the labs might be difficult using the DSL used by Githug

In light of the above, and knowing that I am generally a busy man. I thought I would discuss this with you prior to attempting to do it, in case you think it might not be as useful of a development as I initially thought it was.

Looking forward to your thoughts and suggestions to ensure I do not waste my time doing something that has shortcomings or issues that I am unable to foresee.

Regards,
Orwa.

**Comment by Gazler** [comment]
Hey,

Thanks for the suggestion. This isn't something I'd be interested in maintaining or suporting, however you are welcome run with your own fork for this purpose.

This project was designed to be a part of git learning experience, so if a combination of Git Immersion and githug works for people that's great. I know some universities have used it as part of their curriculum in the past along with their lectures, so there is precedence for this type of learning.

Thanks,
Gary
